### ISSUE TITLE
Access token invalid error with the new update

### ISSUE THREAD

**Issue by qt1211** [GearPlug/pipedrive-python#11]
Hi,
I was using the previous version which was using api_base_url and access_token to access the database. 
With the new update, I input client_id, client_secret, redirect_url and access_token but it kept throwing "UnauthorizedError: Invalid token: access token is invalid" error. 
I'm not quite sure how to find the code for this line:
token = client.exchange_code('REDIRECT_URL', 'CODE')
Any help would be much appreciated.

**Comment by ingmferrer** [comment]
I'm validating this, in the meantime you can still use the previous version:

`pip install pipedrive-python-lib==0.1.3`

**Comment by ingmferrer** [comment]
This is now fixed in the new release. Please refer to #12 for more information.

If you have another problem, please open a new ticket.
