### ISSUE TITLE
Add product to deal

### ISSUE THREAD

**Issue by brett-nuske-alliancesoftware** [GearPlug/pipedrive-python#13]
I didn't see any library function to add a product to a deal.

I was able to accomplish this with the following:

```
def add_product_to_deal(self, data, **kwargs):
        url = f'deals/{data["id"]}/products'
        return self.client.deals._client._post(
            self.client.deals._client.BASE_URL + url, json=data, **kwargs
        )
```

Perhaps this functionality could be added to the library.

**Comment by ingmferrer** [comment]
Thanks. It was added in the latest version.
