### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by sowinski** [GearPlug/pipedrive-python#15]
Hi,

installed with pip3 and got this error.

```
python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pipedrive.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pipedrive.client'

```

**Comment by ingmferrer** [comment]
Please, check if your folder is named 'pipedrive' as the library.

**Comment by kapsoft1** [comment]
Hi,

I have the same problem and when looking at the __init__.py file it is empty, any update coming soon ?

**Comment by rosselot212** [comment]
does it matter that the module is installed in pipedrive-python-lib when running pip list - should this not be "pipedrive".

**Comment by ingmferrer** [comment]
Sorry for the late response, it doesn't matter, when we tried to upload the library in pypi.org the "pipedrive" name was already taken so we changed the name only for pypi.org but we still use "pipedrive" for the import code.

I hope this make sense.
