### ISSUE TITLE
Problems with API token

### ISSUE THREAD

**Issue by ernests** [GearPlug/pipedrive-python#26]
Now when you choose to use API token, the logic in Tutorial is to set domain and token. But it doesn't work. It returns 500.

The problem is logic in Client() module. If `domain` isn't provided `BASE_URL` will stay 'https://api-proxy.pipedrive.com/'. If it is provided, `BASE_URL` will become `'domain' + 'v1/'`. I don't know why one has to provide company Pipedrive domain as it doesn't work.

Quick fix: 
`client.BASE_URL = "https://api-proxy.pipedrive.com/v1/"`
Now all the methods work like a charm. Maybe I don't understand something. Then documentation should be updated.

**Comment by danielelodola** [comment]
Hi @ernests, I'm getting the same issue as you.

Where exactly do you declare the BASE_URL value please? In the actual script making the various calls? Before / after setting the API token?
