### ISSUE TITLE
Add function timeline in lib

### ISSUE THREAD

**Issue by fabiano-teichmann** [GearPlug/pipedrive-python#4]
Hello guys, i love yours lib, is easy utilization, but lib is necessary include function for get deals with timeline. I implemented this in my code:

   def get_deals_timeline(self, deal_id=None, **kwargs):
        if deal_id is not None:
            url = "deals/timeline{0}".format(deal_id)
        else:
            url = "deals/timeline"
        return self._get(url, **kwargs)

**Comment by yagss** [comment]
Hello there, 
Glad to me to hear that, however you should do a pull request with your contribution.
Regards
