### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by aaroneden** [GearPlug/pipedrive-python#8]
In looking at the Client.py code it doesn't appear this wrapper handles paging, right?  

For example, if I use get_persons and PD sends back 1000 records I will only get the first 500.

I don't see any code that makes me think it would handle paging, but want to be 100% sure as I'm fairly new to Python.  If I'm understanding correctly, I'll work to add paging as I'll need it for the script I'm putting together.

Thanks,
Aaron

**Comment by yagss** [comment]
Hello aaroneden
Take a look of this to know about pipedrive API pagination:
https://pipedrive.readme.io/docs/core-api-concepts-responses
https://pipedrive.readme.io/docs/core-api-concepts-pagination

**Comment by aaroneden** [comment]
Thanks Yordy — I understand how pipedrive handles pagination.  My question
was will the “pipedrive-python” wrapper properly handle pagination today?

Aaron Eden
520-360-7193
Co-founder and Chief Operating Officer
Moves the Needle
<http://www.movestheneedle.com>
*We bring an entrepreneurial spirit to the enterprise.*

On July 23, 2019 at 12:21:39 PM, Yordy Gelvez (notifications@github.com)
wrote:

Hello aaroneden
Take a look of this to know about pipedrive API pagination:
https://pipedrive.readme.io/docs/core-api-concepts-responses
https://pipedrive.readme.io/docs/core-api-concepts-pagination

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GearPlug/pipedrive-python/issues/8?email_source=notifications&email_token=AFAWSA3XTGV37KI7MHHPCS3QA5K4HA5CNFSM4IF7MPRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2UFFQQ#issuecomment-514347714>,
or mute the thread

**Comment by yagss** [comment]
Currently the wrapper does not handle pagination automatically, but many responses from de PD API contain the attr `additional_data` wich contains pagination information.
It looks like this:
`persons = client.get_persons(start=0, limit=4, more_items_in_collection=True)`

This will get a response from PD that will contain the additional_data that looks like this:

`{'pagination': {'start': 0, 'limit': 4, 'more_items_in_collection': True, 'next_start': 4}}`

This is a good staring point to add pagination support to the wrapper.

**Comment by aaroneden** [comment]
I’ll give it a shot, thanks!

**Comment by DuckHawk123** [comment]
Did you get pagination to work?
